# Generated by Django 3.2 on 2021-04-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic_url', models.CharField(max_length=3000)),
                ('phone_number', models.IntegerField()),
                ('facebook', models.TextField()),
                ('instagram', models.CharField(max_length=200)),
            ],
        ),
    ]
