# Generated by Django 3.2 on 2021-04-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20210427_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='twitter',
            field=models.CharField(default='gaddafi', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='facebook',
            field=models.CharField(max_length=300),
        ),
    ]
