# Generated by Django 3.2 on 2021-04-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_student_profile_pic_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile_pic_url',
            new_name='image',
        ),
    ]
